#!/bin/sh

QVDIR=$HOME/.quickviewer

if [ ! -d $QVDIR ] ; then
  mkdir $QVDIR
fi
if [ ! -e $QVDIR/thumbnail.sqlite3.db ] ; then
  cp $APPDIR/var/database/thumbnail.sqlite3.db $QVDIR
fi

#printenv

$APPDIR/usr/bin/QuickViewer "$@"
