#!/bin/bash

QVDIR=$HOME/.quickviewer

if [ ! -d $QVDIR ] ; then
  mkdir $QVDIR
fi
if [ ! -e $QVDIR/thumbnail.sqlite3.db ] ; then
  cp $APPDIR/var/database/thumbnail.sqlite3.db $QVDIR
fi

# file paths to full paths
arr=()
for v in "$@"
do
  if [ -e $v ] ; then
    v=`readlink -f "$v"`
  fi
  arr=("${arr[@]}" "$v")
done

#printenv

$APPDIR/usr/bin/QuickViewer "${arr[@]}"
