# TODO: AesOpt, CrcOpt, XzCrc64Opt

add_definitions(
    -DQT7Z_STATIC_LINK
    -DUNICODE
    -D_UNICODE
    -DWIN_LONG_PATH
    -D_7ZIP_LARGE_PAGES
    -DSUPPORT_DEVICE_FILE
)

set(7Z_SRCS
    # C
    "7zip/C/7zCrc.c"
    "7zip/C/7zCrcOpt.c"
    "7zip/C/7zStream.c"
    "7zip/C/Aes.c"
    "7zip/C/AesOpt.c"
    "7zip/C/Alloc.c"
    "7zip/C/Bcj2.c"
    "7zip/C/Bcj2Enc.c"
    "7zip/C/Bra.c"
    "7zip/C/Bra86.c"
    "7zip/C/BraIA64.c"
    "7zip/C/CpuArch.c"
    "7zip/C/Delta.c"
    "7zip/C/LzFind.c"
    "7zip/C/LzFindMt.c"
    "7zip/C/Lzma2Dec.c"
    "7zip/C/Lzma2Enc.c"
    "7zip/C/LzmaDec.c"
    "7zip/C/LzmaEnc.c"
    "7zip/C/MtCoder.c"
    "7zip/C/Ppmd7.c"
    "7zip/C/Ppmd7Dec.c"
    "7zip/C/Ppmd7Enc.c"
    "7zip/C/Sha256.c"
    "7zip/C/Sort.c"
    "7zip/C/Threads.c"
    "7zip/C/Xz.c"
    "7zip/C/XzDec.c"
    "7zip/C/XzEnc.c"
    "7zip/C/XzIn.c"

    # Common
    "7zip/CPP/Common/CommandLineParser.cpp"
    "7zip/CPP/Common/CRC.cpp"
    "7zip/CPP/Common/CrcReg.cpp"
    "7zip/CPP/Common/IntToString.cpp"
    "7zip/CPP/Common/ListFileUtils.cpp"
    "7zip/CPP/Common/NewHandler.cpp"
    "7zip/CPP/Common/StdInStream.cpp"
    "7zip/CPP/Common/StdOutStream.cpp"
    "7zip/CPP/Common/MyString.cpp"
    "7zip/CPP/Common/StringConvert.cpp"
    "7zip/CPP/Common/StringToInt.cpp"
    "7zip/CPP/Common/UTFConvert.cpp"
    "7zip/CPP/Common/MyVector.cpp"
    "7zip/CPP/Common/MyWindows.cpp"
    "7zip/CPP/Common/Wildcard.cpp"
    "7zip/CPP/Common/XzCrc64Init.cpp"
    "7zip/CPP/Common/XzCrc64Reg.cpp"
    "7zip/CPP/Common/Sha256Reg.cpp"

    # Win
    "7zip/CPP/Windows/DLL.cpp"
    "7zip/CPP/Windows/ErrorMsg.cpp"
    "7zip/CPP/Windows/FileDir.cpp"
    "7zip/CPP/Windows/FileFind.cpp"
    "7zip/CPP/Windows/FileIO.cpp"
    "7zip/CPP/Windows/FileLink.cpp"
    "7zip/CPP/Windows/FileName.cpp"
    "7zip/CPP/Windows/FileSystem.cpp"
    "7zip/CPP/Windows/MemoryLock.cpp"
    "7zip/CPP/Windows/PropVariant.cpp"
    "7zip/CPP/Windows/PropVariantConv.cpp"
    "7zip/CPP/Windows/Synchronization.cpp"
    "7zip/CPP/Windows/System.cpp"
    "7zip/CPP/Windows/TimeUtils.cpp"

    # 7zip common
    "7zip/CPP/7zip/Common/CreateCoder.cpp"
    "7zip/CPP/7zip/Common/CWrappers.cpp"
    "7zip/CPP/7zip/Common/FilePathAutoRename.cpp"
    "7zip/CPP/7zip/Common/FileStreams.cpp"
    "7zip/CPP/7zip/Common/FilterCoder.cpp"
    "7zip/CPP/7zip/Common/InBuffer.cpp"
    "7zip/CPP/7zip/Common/InOutTempBuffer.cpp"
    "7zip/CPP/7zip/Common/LimitedStreams.cpp"
    "7zip/CPP/7zip/Common/MethodId.cpp"
    "7zip/CPP/7zip/Common/MethodProps.cpp"
    "7zip/CPP/7zip/Common/OffsetStream.cpp"
    "7zip/CPP/7zip/Common/OutBuffer.cpp"
    "7zip/CPP/7zip/Common/ProgressUtils.cpp"
    "7zip/CPP/7zip/Common/PropId.cpp"
    "7zip/CPP/7zip/Common/StreamBinder.cpp"
    "7zip/CPP/7zip/Common/StreamObjects.cpp"
    "7zip/CPP/7zip/Common/StreamUtils.cpp"
    "7zip/CPP/7zip/Common/UniqBlocks.cpp"
    "7zip/CPP/7zip/Common/VirtThread.cpp"

    "7zip/CPP/7zip/Archive/LzmaHandler.cpp"
    "7zip/CPP/7zip/Archive/SplitHandler.cpp"
    "7zip/CPP/7zip/Archive/XzHandler.cpp"

    "7zip/CPP/7zip/Archive/Common/CoderMixer2.cpp"
    "7zip/CPP/7zip/Archive/Common/DummyOutStream.cpp"
    "7zip/CPP/7zip/Archive/Common/HandlerOut.cpp"
    "7zip/CPP/7zip/Archive/Common/InStreamWithCRC.cpp"
    "7zip/CPP/7zip/Archive/Common/ItemNameUtils.cpp"
    "7zip/CPP/7zip/Archive/Common/MultiStream.cpp"
    "7zip/CPP/7zip/Archive/Common/OutStreamWithCRC.cpp"
    "7zip/CPP/7zip/Archive/Common/ParseProperties.cpp"

    "7zip/CPP/7zip/Archive/7z/7zCompressionMode.cpp"
    "7zip/CPP/7zip/Archive/7z/7zDecode.cpp"
    "7zip/CPP/7zip/Archive/7z/7zEncode.cpp"
    "7zip/CPP/7zip/Archive/7z/7zExtract.cpp"
    "7zip/CPP/7zip/Archive/7z/7zFolderInStream.cpp"
    "7zip/CPP/7zip/Archive/7z/7zHandler.cpp"
    "7zip/CPP/7zip/Archive/7z/7zHandlerOut.cpp"
    "7zip/CPP/7zip/Archive/7z/7zHeader.cpp"
    "7zip/CPP/7zip/Archive/7z/7zIn.cpp"
    "7zip/CPP/7zip/Archive/7z/7zOut.cpp"
    "7zip/CPP/7zip/Archive/7z/7zProperties.cpp"
    "7zip/CPP/7zip/Archive/7z/7zSpecStream.cpp"
    "7zip/CPP/7zip/Archive/7z/7zUpdate.cpp"
    "7zip/CPP/7zip/Archive/7z/7zRegister.cpp"

    # Compress
    "7zip/CPP/7zip/Compress/Bcj2Coder.cpp"
    "7zip/CPP/7zip/Compress/Bcj2Register.cpp"
    "7zip/CPP/7zip/Compress/BcjCoder.cpp"
    "7zip/CPP/7zip/Compress/BcjRegister.cpp"
    "7zip/CPP/7zip/Compress/BranchMisc.cpp"
    "7zip/CPP/7zip/Compress/BranchRegister.cpp"
    "7zip/CPP/7zip/Compress/ByteSwap.cpp"
    "7zip/CPP/7zip/Compress/CopyCoder.cpp"
    "7zip/CPP/7zip/Compress/CopyRegister.cpp"
    "7zip/CPP/7zip/Compress/DeltaFilter.cpp"
    "7zip/CPP/7zip/Compress/Lzma2Decoder.cpp"
    "7zip/CPP/7zip/Compress/Lzma2Encoder.cpp"
    "7zip/CPP/7zip/Compress/Lzma2Register.cpp"
    "7zip/CPP/7zip/Compress/LzmaDecoder.cpp"
    "7zip/CPP/7zip/Compress/LzmaEncoder.cpp"
    "7zip/CPP/7zip/Compress/LzmaRegister.cpp"
    "7zip/CPP/7zip/Compress/PpmdDecoder.cpp"
    "7zip/CPP/7zip/Compress/PpmdEncoder.cpp"
    "7zip/CPP/7zip/Compress/PpmdRegister.cpp"
    "7zip/CPP/7zip/Compress/XzDecoder.cpp"
    "7zip/CPP/7zip/Compress/XzEncoder.cpp"

    # Crypto
    "7zip/CPP/7zip/Crypto/7zAes.cpp"
    "7zip/CPP/7zip/Crypto/7zAesRegister.cpp"
    "7zip/CPP/7zip/Crypto/MyAes.cpp"
    "7zip/CPP/7zip/Crypto/MyAesReg.cpp"
    "7zip/CPP/7zip/Crypto/RandGen.cpp"

    # UI
    "7zip/CPP/7zip/UI/Common/ArchiveExtractCallback.cpp"
    "7zip/CPP/7zip/UI/Common/ArchiveOpenCallback.cpp"
    "7zip/CPP/7zip/UI/Common/DefaultName.cpp"
    "7zip/CPP/7zip/UI/Common/Extract.cpp"
    "7zip/CPP/7zip/UI/Common/ExtractingFilePath.cpp"
    "7zip/CPP/7zip/UI/Common/LoadCodecs.cpp"
    "7zip/CPP/7zip/UI/Common/OpenArchive.cpp"
    "7zip/CPP/7zip/UI/Common/PropIDUtils.cpp"
    "7zip/CPP/7zip/UI/Common/SetProperties.cpp"
)
